language: ruby
rvm:
  - 2.3.1
before_install:
  - gem update --system
  - gem --version
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database ripped_test;' -U postgres
